XML 1 - Find the Score

In [ ]:
import sys
import xml.etree.ElementTree as etree

def get_attr_number(node):
    return len(node.attrib) + sum([get_attr_number(child) for child in node])
    
if __name__ == '__main__':
    sys.stdin.readline()
    xml = sys.stdin.read()
    tree = etree.ElementTree(etree.fromstring(xml))
    root = tree.getroot()
    print(get_attr_number(root))

xml2-find-the-maximum-depth

In [ ]:
import xml.etree.ElementTree as etree

maxdepth = 0
def depth(elem, level):
    global maxdepth
    if (level == maxdepth):
        maxdepth += 1

    for child in elem:
        depth(child, level + 1)

if __name__ == '__main__':
    n = int(input())
    xml = ""
    for i in range(n):
        xml =  xml + input() + "\n"
    tree = etree.ElementTree(etree.fromstring(xml))
    depth(tree.getroot(), -1)
    print(maxdepth)

6
<feed xml:lang='en'>
  <title>HackerRank</title>
  <subtitle lang='en'>Programming challenges</subtitle>
  <link rel='alternate' type='text/html' href='http://hackerrank.com/'/>
  <updated>2013-12-25T12:00:00</updated>
</feed>
1


Standardize Mobile Number Using Decorators

In [ ]:
def wrapper(f):
    def fun(l):
       f(['+91 ' + c[-10:-5] + ' ' + c[-5:] for c in l])      

        
            
        # complete the function
    return fun

@wrapper
def sort_phone(l):
    print(*sorted(l), sep='\n')

if __name__ == '__main__':
    l = [input() for _ in range(int(input()))]
    sort_phone(l) 


3
07895462130
919875641230
9195969878
+91 78954 62130
+91 91959 69878
+91 98756 41230


decorators-2-name-directory

In [ ]:
import operator

def person_lister(f):
    def inner(people):
       return map(f, sorted(people, key=lambda x: int(x[2])))
    return inner

@person_lister
def name_format(person):
    return ("Mr. " if person[3] == "M" else "Ms. ") + person[0] + " " + person[1]

if __name__ == '__main__':
    people = [input().split() for i in range(int(input()))]
    print(*name_format(people), sep='\n')

3
Mike Thomson 20 M
Robert Bustle 32 M
Andria Bustle 30 F
Mr. Mike Thomson
Ms. Andria Bustle
Mr. Robert Bustle


Arrays

In [ ]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    
    arr= numpy.array(arr,float)

    return arr[::-1]

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


Shape and Reshape

In [ ]:
import numpy
def d_arrays(arr):
    arr = numpy.array(arr,int)
    arr.shape=(3,3)
    return arr
    
    
arr =input().strip().split(' ')
result = d_arrays(arr)
print(result)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Transpose and Flatten

In [ ]:
import numpy as np

def transpoed_array(arr):
    arr = np.transpose(arr)
    return arr
def flattend_array(arr):
    arr= arr.flatten()
    return arr
n,m =input().strip().split()
arr_l=[]
for _ in range(int(n)):
    arr_l.append(input().strip().split())
arr_d = np.array(arr_l,int)
print(transpoed_array(arr_d))
print(flattend_array(arr_d))



2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


Concatenate

In [ ]:
import numpy as np

n,m,p = list(map(int,input().strip().split()))
arr_l=[]
arr_l_two=[]
for _ in range(n):
    arr_l.append(input().strip().split())
    
for _ in range(m):
    arr_l_two.append(input().strip().split())
arr_d = np.array(arr_l,int)
arr_d_two = np.array(arr_l_two,int)
print(np.concatenate((arr_d,arr_d_two)))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


Concatenate

In [ ]:
import numpy as np

N = tuple(map(int, input().split()))
print(np.zeros(N, int))
print(np.ones(N, int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


Eye and Identity

In [ ]:
import numpy as np
np.set_printoptions(legacy="1.13")
n,m= list(map(int,input().strip().split()))
print(np.eye(n,m, k=0))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Floor, Ceil and Rint

In [ ]:
import numpy as np
np.set_printoptions(legacy="1.13")
n= input().strip().split()
arr=np.array(n,float)
print(np.floor(arr))
print(np.ceil(arr))
print(np.rint(arr))


1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


Sum and Prod


In [ ]:
import numpy as np
n,m = list(map(int,input().strip().split()))
x_list=[]
for _ in range(n):
    x = input().strip().split()
    x_list.append(x)
n_array = np.array((x_list),int)
sum_array =np.sum(n_array,axis=0)
print(np.prod(sum_array))

2 2
1 2
3 4
24


Min and Max

In [ ]:
import numpy as np
n,m = list(map(int,input().strip().split()))
arr_l = []
for _ in range(n):
    m = input().strip().split()
    arr_l.append(m)
arr_m = np.array((arr_l),int)
arr_m_min = np.min(arr_m,axis=1)
arr_prod = np.max(arr_m_min)
print(arr_prod)

4 2
2 5
3 7
1 3
4 0
3


Array Mathematics

In [ ]:
import numpy as np
n,m=list(map(int,input().split()))
a_arr = np.array([input().split() for _ in range(n)],int)
b_arr = np.array([input().split() for _ in range(n)],int)
    
print(np.add(a_arr,b_arr))
print(np.subtract(a_arr,b_arr))
print(np.multiply(a_arr,b_arr))
print(np.floor_divide(a_arr,b_arr))
print(np.mod(a_arr,b_arr))
print(np.power(a_arr,b_arr))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


Dot and Cross

In [ ]:
import numpy as np
n = int(input())
a = np.array([list(map(int,input().split())) for _ in range(n)])
b = np.array([list(map(int,input().split())) for _ in range(n)])
print(np.dot(a,b))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


Inner and Outer

In [ ]:
import numpy as np

a = np.array(list(map(int,input().split())))
b = np.array(list(map(int,input().split())))
print(np.inner(a,b))
print(np.outer(a,b))

0 1
2 3
3
[[0 0]
 [2 3]]


Polynomials

In [ ]:
import numpy as np

arr_p = np.array(list(map(float,input().split())))
x = int(input())
print(np.polyval(arr_p,x))


1.1 2 3
0
3.0


Linear Algebra

In [ ]:
import numpy as np

n = int(input())
a = np.array([list(map(float,input().split())) for _ in range(n)])
print(round(np.linalg.det(a),2))

2
1.1 1.1
1.1 1.1
0.0


Mean, Var, and Std

In [ ]:
import numpy as np
n,m =list(map(int,input().split()))
m = np.array([input().split() for _ in range(n)],float)

print(np.mean(m,axis=1))
print(np.var(m,axis=0))
print(np.round(np.std(m), 11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


Zipped!

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
n, x = list(map(int,input().split()))
subject_scores = [list(map(float,input().split())) for _ in range(x)]
students_scores = list(zip(*subject_scores))
for i in students_scores:
    print(sum(i)/x)
    

5 3
89 90 78 93 80
90 91 85 88 86
91 92 83 89 90.5
90.0
91.0
82.0
90.0
85.5


Input()

In [ ]:
if __name__ == "__main__":
    x, k = map(int, input().strip().split())
    string = input().strip()
    
    if eval(string) == k:
        print(True)
    else:
        print(False)

1 4
x**3 + x**2 + x + 1
True


Python Evaluation

In [ ]:
eval(input())

print(2 + 3)
5


Any or All

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
_ = input()
n = input().split()
print(all([int(i) > 0 for i in n]) and any([j == j[::-1] for j in n]))

5
12 9 61 5 14
True


ginorts

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
s = input()
lower_s=""
upper_s=""
odd_d=""
even_d=""
for i in s:
    if i.islower():
        lower_s+=i
    elif(i.isupper()):
        upper_s+=i
    elif(i.isnumeric()):
        if int(i) % 2==1:
            odd_d+=i
        elif int(i) % 2==0:
            even_d+=i
new_s = sorted(lower_s)+sorted(upper_s)+sorted(odd_d)+sorted(even_d)
print("".join(new_s))


Sorting1234
ginortS1324


python-sort-sort athletes 

In [ ]:
#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    k = int(input())
    
    arr.sort(key = lambda x : x[k])
    for i in arr:
        print(*i,sep=' ')


5 3
10 2 5
7 1 0
9 9 9
1 23 12
6 5 9
1
7 1 0
10 2 5
6 5 9
9 9 9
1 23 12


words-score

In [ ]:
def is_vowel(letter):
    return letter in ['a', 'e', 'i', 'o', 'u', 'y']

def score_words(words):
    score = 0
    for word in words:
        num_vowels = 0
        for letter in word:
            if is_vowel(letter):
                num_vowels += 1
        if num_vowels % 2 == 0:
            score += 2
        elif num_vowels % 2 == 1:
            score += 1
    return score


n = int(input())
words = input().split()
print(score_words(words))

2
hacker book
4


maximize it

In [ ]:
from itertools import *

K, M = map(int, input().split())
N = []

for _ in range(K):
    N.append(map(int, input().split()[1:]))
MAX = 0
for i in product(*N):
    MAX = max(sum(map(lambda x: x**2, i))%M, MAX)

print(MAX)


3 1000
2 5 4
3 7 8 9
5 5 7 8 9 10
206
